<?php
if(!defined('BP_SILENCE_THEME_NOTICE')) define( 'BP_SILENCE_THEME_NOTICE', true );
if(!defined('STAYPRESS_PROPERTY_POST_TYPE')) define('STAYPRESS_PROPERTY_POST_TYPE', 'property');
if(!defined('STAYPRESS_CONTACT_POST_TYPE')) define('STAYPRESS_CONTACT_POST_TYPE', 'contact');
if(!defined('STAYPRESS_DESTINATION_POST_TYPE')) define('STAYPRESS_DESTINATION_POST_TYPE', 'destination');

if(!defined('STAYPRESS_GLOBAL_TABLES')) define('STAYPRESS_GLOBAL_TABLES', false);

if(!defined('STAYPRESS_PROPERTY_PER_PAGE')) define('STAYPRESS_PROPERTY_PER_PAGE', 25);

if(!defined('STAYPRESS_ADMIN_PROPERTY_PER_PAGE')) define('STAYPRESS_ADMIN_PROPERTY_PER_PAGE', 15);
?>